//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace TZHSWEET.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PM_Project))]
    [KnownType(typeof(PM_Task))]
    public partial class PM_Attachment: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“ID”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    if (!IsDeserializing)
                    {
                        if (PM_Project != null && PM_Project.ID != value)
                        {
                            PM_Project = null;
                        }
                        if (PM_Task != null && PM_Task.ID != value)
                        {
                            PM_Task = null;
                        }
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _iD;
    
        [DataMember]
        public Nullable<int> ProjectID
        {
            get { return _projectID; }
            set
            {
                if (_projectID != value)
                {
                    _projectID = value;
                    OnPropertyChanged("ProjectID");
                }
            }
        }
        private Nullable<int> _projectID;
    
        [DataMember]
        public Nullable<int> TaskID
        {
            get { return _taskID; }
            set
            {
                if (_taskID != value)
                {
                    _taskID = value;
                    OnPropertyChanged("TaskID");
                }
            }
        }
        private Nullable<int> _taskID;
    
        [DataMember]
        public Nullable<int> FileID
        {
            get { return _fileID; }
            set
            {
                if (_fileID != value)
                {
                    _fileID = value;
                    OnPropertyChanged("FileID");
                }
            }
        }
        private Nullable<int> _fileID;
    
        [DataMember]
        public Nullable<int> AttachmentTyep
        {
            get { return _attachmentTyep; }
            set
            {
                if (_attachmentTyep != value)
                {
                    _attachmentTyep = value;
                    OnPropertyChanged("AttachmentTyep");
                }
            }
        }
        private Nullable<int> _attachmentTyep;
    
        [DataMember]
        public string AttachmentTitle
        {
            get { return _attachmentTitle; }
            set
            {
                if (_attachmentTitle != value)
                {
                    _attachmentTitle = value;
                    OnPropertyChanged("AttachmentTitle");
                }
            }
        }
        private string _attachmentTitle;
    
        [DataMember]
        public string AttachmentPath
        {
            get { return _attachmentPath; }
            set
            {
                if (_attachmentPath != value)
                {
                    _attachmentPath = value;
                    OnPropertyChanged("AttachmentPath");
                }
            }
        }
        private string _attachmentPath;
    
        [DataMember]
        public Nullable<int> UploadUserID
        {
            get { return _uploadUserID; }
            set
            {
                if (_uploadUserID != value)
                {
                    _uploadUserID = value;
                    OnPropertyChanged("UploadUserID");
                }
            }
        }
        private Nullable<int> _uploadUserID;
    
        [DataMember]
        public Nullable<System.DateTime> UploadDate
        {
            get { return _uploadDate; }
            set
            {
                if (_uploadDate != value)
                {
                    _uploadDate = value;
                    OnPropertyChanged("UploadDate");
                }
            }
        }
        private Nullable<System.DateTime> _uploadDate;
    
        [DataMember]
        public Nullable<int> DeletedUserID
        {
            get { return _deletedUserID; }
            set
            {
                if (_deletedUserID != value)
                {
                    _deletedUserID = value;
                    OnPropertyChanged("DeletedUserID");
                }
            }
        }
        private Nullable<int> _deletedUserID;
    
        [DataMember]
        public Nullable<System.DateTime> DeletedDate
        {
            get { return _deletedDate; }
            set
            {
                if (_deletedDate != value)
                {
                    _deletedDate = value;
                    OnPropertyChanged("DeletedDate");
                }
            }
        }
        private Nullable<System.DateTime> _deletedDate;
    
        [DataMember]
        public string RecordStatus
        {
            get { return _recordStatus; }
            set
            {
                if (_recordStatus != value)
                {
                    _recordStatus = value;
                    OnPropertyChanged("RecordStatus");
                }
            }
        }
        private string _recordStatus;
    
        [DataMember]
        public Nullable<bool> IsDeleted
        {
            get { return _isDeleted; }
            set
            {
                if (_isDeleted != value)
                {
                    _isDeleted = value;
                    OnPropertyChanged("IsDeleted");
                }
            }
        }
        private Nullable<bool> _isDeleted;

        #endregion

        #region 导航属性
    
        [DataMember]
        public PM_Project PM_Project
        {
            get { return _pM_Project; }
            set
            {
                if (!ReferenceEquals(_pM_Project, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // 这是识别关系的依赖端，因此主体端在设置后不能更改，
                        // 否则它只能设置为主键值与依赖外键相同的实体。
                        if (ID != value.ID)
                        {
                            throw new InvalidOperationException("仅当依赖端处于“已添加”状态时，才能更改识别关系的主体端。");
                        }
                    }
                    var previousValue = _pM_Project;
                    _pM_Project = value;
                    FixupPM_Project(previousValue);
                    OnNavigationPropertyChanged("PM_Project");
                }
            }
        }
        private PM_Project _pM_Project;
    
        [DataMember]
        public PM_Task PM_Task
        {
            get { return _pM_Task; }
            set
            {
                if (!ReferenceEquals(_pM_Task, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // 这是识别关系的依赖端，因此主体端在设置后不能更改，
                        // 否则它只能设置为主键值与依赖外键相同的实体。
                        if (ID != value.ID)
                        {
                            throw new InvalidOperationException("仅当依赖端处于“已添加”状态时，才能更改识别关系的主体端。");
                        }
                    }
                    var previousValue = _pM_Task;
                    _pM_Task = value;
                    FixupPM_Task(previousValue);
                    OnNavigationPropertyChanged("PM_Task");
                }
            }
        }
        private PM_Task _pM_Task;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        // 此实体类型是至少一个执行级联删除的关联中的依赖端。
        // 此事件处理程序将处理在删除主体端时发生的通知。
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PM_Project = null;
            PM_Task = null;
        }

        #endregion

        #region 关联修复
    
        private void FixupPM_Project(PM_Project previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.PM_Attachment, this))
            {
                previousValue.PM_Attachment = null;
            }
    
            if (PM_Project != null)
            {
                PM_Project.PM_Attachment = this;
                ID = PM_Project.ID;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PM_Project")
                    && (ChangeTracker.OriginalValues["PM_Project"] == PM_Project))
                {
                    ChangeTracker.OriginalValues.Remove("PM_Project");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PM_Project", previousValue);
                }
                if (PM_Project != null && !PM_Project.ChangeTracker.ChangeTrackingEnabled)
                {
                    PM_Project.StartTracking();
                }
            }
        }
    
        private void FixupPM_Task(PM_Task previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.PM_Attachment, this))
            {
                previousValue.PM_Attachment = null;
            }
    
            if (PM_Task != null)
            {
                PM_Task.PM_Attachment = this;
                ID = PM_Task.ID;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PM_Task")
                    && (ChangeTracker.OriginalValues["PM_Task"] == PM_Task))
                {
                    ChangeTracker.OriginalValues.Remove("PM_Task");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PM_Task", previousValue);
                }
                if (PM_Task != null && !PM_Task.ChangeTracker.ChangeTrackingEnabled)
                {
                    PM_Task.StartTracking();
                }
            }
        }

        #endregion

    }
}
