//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace TZHSWEET.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PM_Project))]
    [KnownType(typeof(PM_Documents))]
    public partial class PM_Directorys: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int DirectoryID
        {
            get { return _directoryID; }
            set
            {
                if (_directoryID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“DirectoryID”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _directoryID = value;
                    OnPropertyChanged("DirectoryID");
                }
            }
        }
        private int _directoryID;
    
        [DataMember]
        public string DirectoryName
        {
            get { return _directoryName; }
            set
            {
                if (_directoryName != value)
                {
                    _directoryName = value;
                    OnPropertyChanged("DirectoryName");
                }
            }
        }
        private string _directoryName;
    
        [DataMember]
        public Nullable<int> ParentID
        {
            get { return _parentID; }
            set
            {
                if (_parentID != value)
                {
                    _parentID = value;
                    OnPropertyChanged("ParentID");
                }
            }
        }
        private Nullable<int> _parentID;
    
        [DataMember]
        public Nullable<int> ProjectID
        {
            get { return _projectID; }
            set
            {
                if (_projectID != value)
                {
                    ChangeTracker.RecordOriginalValue("ProjectID", _projectID);
                    if (!IsDeserializing)
                    {
                        if (PM_Project != null && PM_Project.ID != value)
                        {
                            PM_Project = null;
                        }
                    }
                    _projectID = value;
                    OnPropertyChanged("ProjectID");
                }
            }
        }
        private Nullable<int> _projectID;
    
        [DataMember]
        public Nullable<int> CreateUserID
        {
            get { return _createUserID; }
            set
            {
                if (_createUserID != value)
                {
                    _createUserID = value;
                    OnPropertyChanged("CreateUserID");
                }
            }
        }
        private Nullable<int> _createUserID;
    
        [DataMember]
        public string CreateDate
        {
            get { return _createDate; }
            set
            {
                if (_createDate != value)
                {
                    _createDate = value;
                    OnPropertyChanged("CreateDate");
                }
            }
        }
        private string _createDate;
    
        [DataMember]
        public Nullable<int> ModifyUserID
        {
            get { return _modifyUserID; }
            set
            {
                if (_modifyUserID != value)
                {
                    _modifyUserID = value;
                    OnPropertyChanged("ModifyUserID");
                }
            }
        }
        private Nullable<int> _modifyUserID;
    
        [DataMember]
        public Nullable<System.DateTime> ModifyDate
        {
            get { return _modifyDate; }
            set
            {
                if (_modifyDate != value)
                {
                    _modifyDate = value;
                    OnPropertyChanged("ModifyDate");
                }
            }
        }
        private Nullable<System.DateTime> _modifyDate;
    
        [DataMember]
        public string RecordStatus
        {
            get { return _recordStatus; }
            set
            {
                if (_recordStatus != value)
                {
                    _recordStatus = value;
                    OnPropertyChanged("RecordStatus");
                }
            }
        }
        private string _recordStatus;
    
        [DataMember]
        public Nullable<bool> IsDeleted
        {
            get { return _isDeleted; }
            set
            {
                if (_isDeleted != value)
                {
                    _isDeleted = value;
                    OnPropertyChanged("IsDeleted");
                }
            }
        }
        private Nullable<bool> _isDeleted;

        #endregion

        #region 导航属性
    
        [DataMember]
        public PM_Project PM_Project
        {
            get { return _pM_Project; }
            set
            {
                if (!ReferenceEquals(_pM_Project, value))
                {
                    var previousValue = _pM_Project;
                    _pM_Project = value;
                    FixupPM_Project(previousValue);
                    OnNavigationPropertyChanged("PM_Project");
                }
            }
        }
        private PM_Project _pM_Project;
    
        [DataMember]
        public TrackableCollection<PM_Documents> PM_Documents
        {
            get
            {
                if (_pM_Documents == null)
                {
                    _pM_Documents = new TrackableCollection<PM_Documents>();
                    _pM_Documents.CollectionChanged += FixupPM_Documents;
                }
                return _pM_Documents;
            }
            set
            {
                if (!ReferenceEquals(_pM_Documents, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("当启用 ChangeTracking 时，无法设置 FixupChangeTrackingCollection");
                    }
                    if (_pM_Documents != null)
                    {
                        _pM_Documents.CollectionChanged -= FixupPM_Documents;
                    }
                    _pM_Documents = value;
                    if (_pM_Documents != null)
                    {
                        _pM_Documents.CollectionChanged += FixupPM_Documents;
                    }
                    OnNavigationPropertyChanged("PM_Documents");
                }
            }
        }
        private TrackableCollection<PM_Documents> _pM_Documents;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PM_Project = null;
            PM_Documents.Clear();
        }

        #endregion

        #region 关联修复
    
        private void FixupPM_Project(PM_Project previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PM_Directorys.Contains(this))
            {
                previousValue.PM_Directorys.Remove(this);
            }
    
            if (PM_Project != null)
            {
                if (!PM_Project.PM_Directorys.Contains(this))
                {
                    PM_Project.PM_Directorys.Add(this);
                }
    
                ProjectID = PM_Project.ID;
            }
            else if (!skipKeys)
            {
                ProjectID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PM_Project")
                    && (ChangeTracker.OriginalValues["PM_Project"] == PM_Project))
                {
                    ChangeTracker.OriginalValues.Remove("PM_Project");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PM_Project", previousValue);
                }
                if (PM_Project != null && !PM_Project.ChangeTracker.ChangeTrackingEnabled)
                {
                    PM_Project.StartTracking();
                }
            }
        }
    
        private void FixupPM_Documents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PM_Documents item in e.NewItems)
                {
                    item.PM_Directorys = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PM_Documents", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PM_Documents item in e.OldItems)
                {
                    if (ReferenceEquals(item.PM_Directorys, this))
                    {
                        item.PM_Directorys = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PM_Documents", item);
                    }
                }
            }
        }

        #endregion

    }
}
