//------------------------------------------------------------------------------
// <auto-generated>
//     此代码是根据模板生成的。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace TZHSWEET.Entity
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PM_Task))]
    public partial class PM_ProgressLog: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region 基元属性
    
        [DataMember]
        public int ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("属性“ID”是对象键的一部分，不可更改。仅当未跟踪对象或对象处于“已添加”状态时，才能对键属性进行更改。");
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private int _iD;
    
        [DataMember]
        public Nullable<int> TaskID
        {
            get { return _taskID; }
            set
            {
                if (_taskID != value)
                {
                    ChangeTracker.RecordOriginalValue("TaskID", _taskID);
                    if (!IsDeserializing)
                    {
                        if (PM_Task != null && PM_Task.ID != value)
                        {
                            PM_Task = null;
                        }
                    }
                    _taskID = value;
                    OnPropertyChanged("TaskID");
                }
            }
        }
        private Nullable<int> _taskID;
    
        [DataMember]
        public string LogContent
        {
            get { return _logContent; }
            set
            {
                if (_logContent != value)
                {
                    _logContent = value;
                    OnPropertyChanged("LogContent");
                }
            }
        }
        private string _logContent;
    
        [DataMember]
        public Nullable<double> LogProgress
        {
            get { return _logProgress; }
            set
            {
                if (_logProgress != value)
                {
                    _logProgress = value;
                    OnPropertyChanged("LogProgress");
                }
            }
        }
        private Nullable<double> _logProgress;
    
        [DataMember]
        public Nullable<System.DateTime> LogDate
        {
            get { return _logDate; }
            set
            {
                if (_logDate != value)
                {
                    _logDate = value;
                    OnPropertyChanged("LogDate");
                }
            }
        }
        private Nullable<System.DateTime> _logDate;
    
        [DataMember]
        public Nullable<int> LogUserID
        {
            get { return _logUserID; }
            set
            {
                if (_logUserID != value)
                {
                    _logUserID = value;
                    OnPropertyChanged("LogUserID");
                }
            }
        }
        private Nullable<int> _logUserID;

        #endregion

        #region 导航属性
    
        [DataMember]
        public PM_Task PM_Task
        {
            get { return _pM_Task; }
            set
            {
                if (!ReferenceEquals(_pM_Task, value))
                {
                    var previousValue = _pM_Task;
                    _pM_Task = value;
                    FixupPM_Task(previousValue);
                    OnNavigationPropertyChanged("PM_Task");
                }
            }
        }
        private PM_Task _pM_Task;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PM_Task = null;
        }

        #endregion

        #region 关联修复
    
        private void FixupPM_Task(PM_Task previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.PM_ProgressLog.Contains(this))
            {
                previousValue.PM_ProgressLog.Remove(this);
            }
    
            if (PM_Task != null)
            {
                if (!PM_Task.PM_ProgressLog.Contains(this))
                {
                    PM_Task.PM_ProgressLog.Add(this);
                }
    
                TaskID = PM_Task.ID;
            }
            else if (!skipKeys)
            {
                TaskID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PM_Task")
                    && (ChangeTracker.OriginalValues["PM_Task"] == PM_Task))
                {
                    ChangeTracker.OriginalValues.Remove("PM_Task");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PM_Task", previousValue);
                }
                if (PM_Task != null && !PM_Task.ChangeTracker.ChangeTrackingEnabled)
                {
                    PM_Task.StartTracking();
                }
            }
        }

        #endregion

    }
}
